'use client'

import { AnimatePresence, motion } from 'motion/react'
import { useNavigate } from '@tanstack/react-router'
import { HugeiconsIcon } from '@hugeicons/react'
import { Cancel01Icon } from '@hugeicons/core-free-icons'
import type { DailyBriefing } from '@/types/daily-brief'
import { Markdown } from '@/components/prompt-kit/markdown'

interface DailyBriefModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  briefing: DailyBriefing | null
  onRefresh?: () => void
  isRefreshing?: boolean
}

export function DailyBriefModal({
  open,
  onOpenChange,
  briefing,
  onRefresh,
  isRefreshing = false,
}: DailyBriefModalProps) {
  const navigate = useNavigate()

  if (!open || !briefing) return null

  const handleNavigateInbox = () => {
    onOpenChange(false)
    navigate({ to: '/inbox' })
  }

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
        {/* Backdrop */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 bg-black/75 backdrop-blur-sm"
          onClick={() => onOpenChange(false)}
        />

        {/* Modal Window */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 10 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 10 }}
          transition={{ duration: 0.15 }}
          className="relative z-10 flex flex-col w-full max-w-4xl max-h-[88vh] rounded-2xl border border-neutral-800 bg-[#121316] shadow-2xl overflow-hidden"
          style={{ background: 'var(--theme-card)' }}
        >
          {/* Header */}
          <div className="flex items-center justify-between border-b border-neutral-800/80 px-6 py-4 bg-neutral-900/40">
            <div className="flex items-center gap-3">
              <span className="text-2xl p-2 rounded-xl bg-indigo-500/10 border border-indigo-500/20">
                {briefing.agentEmoji || '👔'}
              </span>
              <div>
                <div className="flex items-center gap-2">
                  <h2 className="text-base font-semibold text-neutral-100">
                    {briefing.title}
                  </h2>
                  <span
                    className={`text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded-full ${
                      briefing.isManual
                        ? 'bg-amber-500/20 text-amber-300 border border-amber-500/30'
                        : 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/30'
                    }`}
                  >
                    {briefing.isManual ? 'Manual Run' : 'Scheduled Morning Brief'}
                  </span>
                </div>
                <p className="text-xs text-neutral-400 mt-0.5">
                  Generated by {briefing.agentName} • {new Date(briefing.generatedAt).toLocaleString()} ({briefing.timezone})
                </p>
              </div>
            </div>

            <div className="flex items-center gap-2">
              {onRefresh && (
                <button
                  type="button"
                  disabled={isRefreshing}
                  onClick={onRefresh}
                  className="px-3 py-1.5 text-xs font-medium text-neutral-300 hover:text-white bg-neutral-800/80 hover:bg-neutral-700/80 border border-neutral-700/60 rounded-lg transition-colors cursor-pointer disabled:opacity-50"
                >
                  {isRefreshing ? 'Regenerating...' : 'Regenerate'}
                </button>
              )}
              <button
                type="button"
                onClick={() => onOpenChange(false)}
                className="p-1.5 text-neutral-400 hover:text-neutral-200 hover:bg-neutral-800 rounded-lg transition-colors cursor-pointer"
                aria-label="Close"
              >
                <HugeiconsIcon icon={Cancel01Icon} className="w-5 h-5" />
              </button>
            </div>
          </div>

          {/* Quick Metrics Bar */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 px-6 py-2.5 bg-neutral-950/40 border-b border-neutral-800/60 text-xs">
            <div className="flex items-center gap-1.5">
              <span className="text-rose-400 font-bold text-sm">
                {briefing.sourceSummaryCounts.needsAttentionCount}
              </span>
              <span className="text-neutral-400">Needs Attention</span>
            </div>
            <div className="flex items-center gap-1.5">
              <span className="text-amber-400 font-bold text-sm">
                {briefing.sourceSummaryCounts.waitingCount}
              </span>
              <span className="text-neutral-400">Waiting / Review</span>
            </div>
            <div className="flex items-center gap-1.5">
              <span className="text-indigo-400 font-bold text-sm">
                {briefing.sourceSummaryCounts.inProgressCount}
              </span>
              <span className="text-neutral-400">In Progress</span>
            </div>
            <div className="flex items-center gap-1.5">
              <span className="text-emerald-400 font-bold text-sm">
                {briefing.sourceSummaryCounts.totalCashBalance !== undefined
                  ? `${briefing.sourceSummaryCounts.currency || 'MYR'} ${briefing.sourceSummaryCounts.totalCashBalance.toLocaleString()}`
                  : '—'}
              </span>
              <span className="text-neutral-400">Cash Reserves</span>
            </div>
          </div>

          {/* Markdown Content */}
          <div className="flex-1 overflow-y-auto px-6 py-5 space-y-4 text-neutral-200 leading-relaxed text-sm">
            <Markdown content={briefing.markdown} />
          </div>

          {/* Footer */}
          <div className="flex items-center justify-between border-t border-neutral-800/80 px-6 py-3.5 bg-neutral-900/40">
            <div className="text-xs text-neutral-400">
              Audit ID: <code className="text-neutral-300 font-mono text-[11px]">{briefing.id}</code>
            </div>
            <div className="flex items-center gap-3">
              <button
                type="button"
                onClick={handleNavigateInbox}
                className="px-3.5 py-1.5 text-xs font-medium text-indigo-300 bg-indigo-950/40 hover:bg-indigo-900/50 border border-indigo-700/50 rounded-lg transition-colors cursor-pointer flex items-center gap-1.5"
              >
                Go to Work Inbox &rarr;
              </button>
              <button
                type="button"
                onClick={() => onOpenChange(false)}
                className="px-3.5 py-1.5 text-xs font-medium text-neutral-300 hover:text-white bg-neutral-800 hover:bg-neutral-700 border border-neutral-700 rounded-lg transition-colors cursor-pointer"
              >
                Close
              </button>
            </div>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  )
}
